# Our chef setup no longer overwrites this file...
development:
  version: '2.0.5'
  morphology: stem_en
  index_exact_words: 1
  mem_limit: 528M
  listen: 127.0.0.1
  compat_sphinxql_magics: 0
  max_matches: 10000
test:
  version: '2.0.5'
  morphology: stem_en
  index_exact_words: 1
  max_matches: 10000
staging:
  morphology: stem_en
  index_exact_words: 1
  address: sphinx.fr2.ec2.internal
  port: 3312
  mem_limit: 528M
  version: '2.1.1-beta'
  compat_sphinxql_magics: 0
  max_matches: 10000
production:
  morphology: stem_en
  index_exact_words: 1
  address: sphinx.fr2.ec2.internal
  port: 3312
  mem_limit: 528M
  version: '2.1.1-beta'
  compat_sphinxql_magics: 0
  max_matches: 10000
